from __future__ import annotations

import json
from collections import defaultdict

from .schemas import ChecklistItem, MergedCommentary, ReviewReport


def _dedupe_checklist(paragraphs: list[MergedCommentary]) -> dict[str, list[str]]:
    grouped: dict[str, list[str]] = defaultdict(list)
    seen: set[tuple[str, str]] = set()
    for paragraph in paragraphs:
        for item in paragraph.checklist:
            key = (item.category, item.item)
            if key in seen:
                continue
            seen.add(key)
            grouped[item.category].append(item.item)
    return dict(grouped)


def _render_checklist(items: list[ChecklistItem]) -> str:
    if not items:
        return "- [ ] No additional actions identified."
    return "\n".join(f"- [ ] {item.item}" for item in items)


def render_report(report: ReviewReport) -> str:
    lines: list[str] = []
    lines.append("# Critical Review — HKGAP Short Paper v1.1")
    lines.append("")
    lines.append(f"*Generated by the HKGAP multi-agent review workflow on {report.generated_at_utc.isoformat()}*")
    lines.append(
        "*Model: "
        f"{report.model_name}. Agents: Structural Biophysicist, Simulation Methodologist, "
        "Statistics & Reproducibility, Prior Art, Science Communicator. "
        "Merged by Editor-in-Chief.*"
    )
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Executive summary")
    lines.append("")
    lines.append(report.executive_summary)
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Paragraph-by-paragraph review")
    lines.append("")

    for paragraph_review in report.paragraphs:
        lines.append(
            f"### §{paragraph_review.paragraph.section} — Paragraph {paragraph_review.paragraph.index}"
        )
        lines.append("")
        lines.append(f"> {paragraph_review.verbatim}")
        lines.append("")
        lines.append("#### 🧭 Explainer-in-Residence")
        lines.append(paragraph_review.explainer_commentary)
        lines.append("")
        lines.append("#### 🔬 Referee critique")
        if paragraph_review.referee_critique:
            for idx, item in enumerate(paragraph_review.referee_critique, start=1):
                lines.append(
                    f"{idx}. **{item.category}**: {item.comment} — *severity: {item.severity}*"
                )
        else:
            lines.append("1. **General**: No major concerns detected for this paragraph. — *severity: minor*")
        lines.append("")
        lines.append("#### ✅ Pre-submission checklist")
        lines.append(_render_checklist(paragraph_review.checklist))
        lines.append("")

        if paragraph_review.integrity_flags:
            lines.append("#### 🚨 Academic-integrity flags")
            for flag in paragraph_review.integrity_flags:
                lines.append(f"- {flag}")
            lines.append("")

        lines.append("---")

    lines.append("")
    lines.append("## Consolidated pre-submission checklist")
    lines.append("")
    consolidated = _dedupe_checklist(report.paragraphs)
    if consolidated:
        for category, items in consolidated.items():
            lines.append(f"### {category}")
            for item in items:
                lines.append(f"- [ ] {item}")
            lines.append("")
    else:
        lines.append("- [ ] No global actions identified.")
        lines.append("")

    lines.append("## Appendix A — Agent-level raw outputs")
    lines.append("")
    for paragraph_review in report.paragraphs:
        title = f"§{paragraph_review.paragraph.section} ¶{paragraph_review.paragraph.index}"
        lines.append(f"<details><summary>{title}</summary>")
        lines.append("")
        for agent_name, payload in paragraph_review.agent_raw_outputs.items():
            lines.append(f"**{agent_name}**")
            lines.append("```json")
            lines.append(json.dumps(payload, indent=2, ensure_ascii=False))
            lines.append("```")
            lines.append("")
        lines.append("</details>")
        lines.append("")

    return "\n".join(lines).strip() + "\n"
